### ISSUE TITLE
UI: We want someone to create basic profile

### ISSUE THREAD

**Issue by duraanali** [duraanali/luuqad#67]
When we click the profile, we want it to link to user profile (No need to add any logic now).

**Comment by duraanali** [comment]
<img width="1432" alt="profile" src="https://github.com/duraanali/luuqad/assets/16447314/a49c44a8-266b-4b59-8118-de3993b0a3e4">

**Comment by duraanali** [comment]
Asc @Suldana, any update?

**Comment by jamaaldev** [comment]
I Added New Page Profile,  I implemented ProfileUser Component still not Finished I need to make a small change about breakpoint devices so that can be identified on Duolin-- website

![Profile Page Screenshot](https://github.com/jamaaldev/luuqad/blob/feature/user-interface/public/github_only/profile_userC.png?raw=true)

**Comment by duraanali** [comment]
Thanks bro, looks good!

**Comment by jamaaldev** [comment]
> Thanks bro, looks good!

thanks, bro also if sista @Suldana is interested she can do the other component I will push this profile page tonight so others can do small components to finish it very soon but first I need to correct the breakpoint tonight insha Allah.

**Comment by duraanali** [comment]
> > Thanks bro, looks good!
> 
> thanks, bro also if sista @Suldana is interested she can do the other component I will push this profile page tonight so others can do small components to finish it very soon but first I need to correct the breakpoint tonight insha Allah.

Ok bro, thanks

**Comment by duraanali** [comment]
Thanks @jamaaldev , I will close this issue.
